[EVNT-525] Fix policy URL
RedHatInsights/eventing-splunk-app pull request #18
Opened 2022-06-08 17:38 UTC by fellipeh

The event of type 'Policy report failed to upload' does not have a
hyperlink, this commit fix it.

2022-06-08 17:42 UTC, CodeHeeler approved these changes
LGTM, thank you!

2022-06-09 11:09 UTC, vkrizan requested changes

2022-06-09 11:09 UTC, vkrizan commented on app/redhat_insights/default/data/ui/views/events.xml
> +| eval url = case(event_type=="drift-baseline-detected", DRIFT_URL.'payload.baseline_id', event_type=="report-upload-failed", POLICIES_URL.'payload.request_id', event_type=="policy-triggered", POLICI
Where does it links to? Is it Payload Tracker?

2022-06-09 11:21 UTC, vkrizan commented on app/redhat_insights/default/data/ui/views/events.xml
> +| eval url = case(event_type=="drift-baseline-detected", DRIFT_URL.'payload.baseline_id', event_type=="report-upload-failed", POLICIES_URL.'payload.request_id', event_type=="policy-triggered", POLICI
It seems that Payload Tracker has the frontend internal only. Nevertheless, @fellipeh can you please check the generated URL?

2022-06-09 11:22 UTC, vkrizan commented
@fellipeh `Policy report failed to upload` is that from Compliance or Policies?

2022-06-09 15:31 UTC, fellipeh commented
@vkrizan Good catch!  

> @fellipeh `Policy report failed to upload` is that from Compliance or Policies?

According to our data, from `Compliance`
<img width="662" alt="image" src="https://user-images.githubusercontent.com/2904206/172885921-22948b83-dfaa-437f-9c38-6eb7a9954935.png">

2022-06-09 15:33 UTC, vkrizan approved these changes

2022-06-09 15:33 UTC, vkrizan commented on app/redhat_insights/default/data/ui/views/events.xml
> +| eval REPORT_URL = "https://console.redhat.com/insights/inventory/"
`s/REPORT_URL/INVENTORY_URL/`

2022-06-09 15:34 UTC, fellipeh commented on app/redhat_insights/default/data/ui/views/events.xml
> +| eval REPORT_URL = "https://console.redhat.com/insights/inventory/"
Done!

2022-06-09 15:36 UTC, merged