[EVNT-742] Fix setup call after update
RedHatInsights/eventing-splunk-app pull request #61
Opened 2022-12-07 14:43 UTC by fellipeh

Fix setup call after update

2022-12-13 22:17 UTC, jpramos123 approved these changes
LGTM

2022-12-14 08:39 UTC, vkrizan requested changes

2022-12-14 08:39 UTC, vkrizan commented on app/redhat_insights/appserver/static/javascript/views/splunk_helpers.js
> +    await create_configuration_file(
Why are we creating the configuration file in a get function?

2022-12-14 08:39 UTC, vkrizan commented on app/redhat_insights/appserver/static/javascript/views/setup_configuration.js
> +      throw new Error(error);
Why are we re-throwing the same error?

2022-12-14 08:39 UTC, vkrizan commented on app/redhat_insights/appserver/static/javascript/views/setup_configuration.js
> +        redirect_to_splunk_app_homepage(app_name);
Shouldn't this check whether the app is configured? If so, then the redirect is outside of its scope.

2022-12-14 08:39 UTC, vkrizan commented on app/redhat_insights/appserver/static/javascript/views/setup.js
> +  console.debug("Entering setup.js");
Left out debug logging.

2022-12-14 08:39 UTC, vkrizan commented on app/redhat_insights/appserver/static/javascript/views/app.js
> +    console.info('SetupIntegration');
Left out debug logging.

2022-12-14 08:39 UTC, vkrizan commented on app/redhat_insights/appserver/static/javascript/views/app.js
> +  Config.is_app_configured(splunk_js_sdk);
Please move this and those Splunk services to appropriate React component so it isn't called on import.

2022-12-14 08:52 UTC, vkrizan commented on app/redhat_insights/appserver/static/javascript/views/app.js
> +  const service = new splunkjs.Service(
Are these services used?

2022-12-14 08:57 UTC, vkrizan commented on app/redhat_insights/appserver/static/javascript/views/app.js
> +  console.debug("Entering app.js");
Left out logging.

2022-12-14 08:57 UTC, vkrizan commented on app/redhat_insights/appserver/static/javascript/views/app.js
> +  const http = new splunkjs.SplunkWebHttp();
`splunkjs` is not defined, or is it?

2022-12-16 14:56 UTC, merged